exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(B8C8D2ff) rgba(294252ff) 45deg
    col.inactive_border = rgba(2D3941ff) rgba(6A5B62ff) 45deg
}

group {
    col.border_active = rgba(B8C8D2ff) rgba(294252ff) 45deg
    col.border_inactive = rgba(2D3941cc) rgba(6A5B62cc) 45deg
    col.border_locked_active = rgba(121212ff) rgba(090909ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
