# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█

# See https://wiki.hyprland.org/Configuring/Keywords/
#  &  https://wiki.hyprland.org/Configuring/Binds/

# Main modifier
$mainMod = Super # super / meta / windows key


# Window/Session actions
bind = Alt, Z, exec, hyprctl dispatch keypress XF86Back
bind = Alt, Y, exec, hyprctl dispatch keypress XF86Forwards

# Application shortcuts
bind = $mainMod, D, exec, vesktop # launch vesktop

# Custom scripts
bind = $mainMod+Alt, Right, exec, $scrPath/swwwallpaper.sh -n # next wallpaper
bind = $mainMod+Alt, Left, exec, $scrPath/swwwallpaper.sh -p # previous wallpaper
bind = $mainMod, F1, exec, $scrPath/keybinds_hint.sh # show keybinds hint

